export const mockQuestions = [
  {
    stat: {
      question_id: 1,
      question__title: 'Two Sum',
      question__title_slug: 'two-sum',
      question__hide: false,
      total_acs: 12223271,
      total_submitted: 23604705,
      frontend_question_id: 1,
      is_new_question: false,
    },
    status: 'ac',
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Two Sum',
    url: 'https://leetcode.com/problems/two-sum',
  },
  {
    stat: {
      question_id: 2,
      question__title: 'Add Two Numbers',
      question__title_slug: 'add-two-numbers',
      question__hide: false,
      total_acs: 4290065,
      total_submitted: 10167202,
      frontend_question_id: 2,
      is_new_question: false,
    },
    status: 'notac',
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Add Two Numbers',
    url: 'https://leetcode.com/problems/add-two-numbers',
  },
  {
    stat: {
      question_id: 3,
      question__title: 'Longest Substring Without Repeating Characters',
      question__title_slug: 'longest-substring-without-repeating-characters',
      question__hide: false,
      total_acs: 5413702,
      total_submitted: 15711931,
      frontend_question_id: 3,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Longest Substring Without Repeating Characters',
    url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters',
  },
  {
    stat: {
      question_id: 4,
      question__title: 'Median of Two Sorted Arrays',
      question__title_slug: 'median-of-two-sorted-arrays',
      question__hide: false,
      total_acs: 2398507,
      total_submitted: 6114481,
      frontend_question_id: 4,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Median of Two Sorted Arrays',
    url: 'https://leetcode.com/problems/median-of-two-sorted-arrays',
  },
  {
    stat: {
      question_id: 5,
      question__title: 'Longest Palindromic Substring',
      question__title_slug: 'longest-palindromic-substring',
      question__hide: false,
      total_acs: 2891131,
      total_submitted: 8614506,
      frontend_question_id: 5,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Longest Palindromic Substring',
    url: 'https://leetcode.com/problems/longest-palindromic-substring',
  },
  {
    stat: {
      question_id: 6,
      question__title: 'Zigzag Conversion',
      question__title_slug: 'zigzag-conversion',
      question__hide: false,
      total_acs: 1239802,
      total_submitted: 2627401,
      frontend_question_id: 6,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Zigzag Conversion',
    url: 'https://leetcode.com/problems/zigzag-conversion',
  },
  {
    stat: {
      question_id: 7,
      question__title: 'Reverse Integer',
      question__title_slug: 'reverse-integer',
      question__hide: false,
      total_acs: 3035027,
      total_submitted: 10720594,
      frontend_question_id: 7,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Reverse Integer',
    url: 'https://leetcode.com/problems/reverse-integer',
  },
  {
    stat: {
      question_id: 8,
      question__title: 'String to Integer (atoi)',
      question__title_slug: 'string-to-integer-atoi',
      question__hide: false,
      total_acs: 1446640,
      total_submitted: 8482716,
      frontend_question_id: 8,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'String to Integer (atoi)',
    url: 'https://leetcode.com/problems/string-to-integer-atoi',
  },
  {
    stat: {
      question_id: 9,
      question__title: 'Palindrome Number',
      question__title_slug: 'palindrome-number',
      question__hide: false,
      total_acs: 4208447,
      total_submitted: 7575416,
      frontend_question_id: 9,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Palindrome Number',
    url: 'https://leetcode.com/problems/palindrome-number',
  },
  {
    stat: {
      question_id: 10,
      question__title: 'Regular Expression Matching',
      question__title_slug: 'regular-expression-matching',
      question__hide: false,
      total_acs: 916814,
      total_submitted: 3265956,
      frontend_question_id: 10,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Regular Expression Matching',
    url: 'https://leetcode.com/problems/regular-expression-matching',
  },
  {
    stat: {
      question_id: 11,
      question__title: 'Container With Most Water',
      question__title_slug: 'container-with-most-water',
      question__hide: false,
      total_acs: 2707037,
      total_submitted: 4942343,
      frontend_question_id: 11,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Container With Most Water',
    url: 'https://leetcode.com/problems/container-with-most-water',
  },
  {
    stat: {
      question_id: 12,
      question__title: 'Integer to Roman',
      question__title_slug: 'integer-to-roman',
      question__hide: false,
      total_acs: 1212897,
      total_submitted: 1891090,
      frontend_question_id: 12,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Integer to Roman',
    url: 'https://leetcode.com/problems/integer-to-roman',
  },
  {
    stat: {
      question_id: 13,
      question__title: 'Roman to Integer',
      question__title_slug: 'roman-to-integer',
      question__hide: false,
      total_acs: 3371087,
      total_submitted: 5566126,
      frontend_question_id: 13,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Roman to Integer',
    url: 'https://leetcode.com/problems/roman-to-integer',
  },
  {
    stat: {
      question_id: 14,
      question__title: 'Longest Common Prefix',
      question__title_slug: 'longest-common-prefix',
      question__hide: false,
      total_acs: 3063770,
      total_submitted: 7244241,
      frontend_question_id: 14,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Longest Common Prefix',
    url: 'https://leetcode.com/problems/longest-common-prefix',
  },
  {
    stat: {
      question_id: 15,
      question__title: '3Sum',
      question__title_slug: '3sum',
      question__hide: false,
      total_acs: 3287526,
      total_submitted: 9643501,
      frontend_question_id: 15,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: '3Sum',
    url: 'https://leetcode.com/problems/3sum',
  },
  {
    stat: {
      question_id: 16,
      question__title: '3Sum Closest',
      question__title_slug: '3sum-closest',
      question__hide: false,
      total_acs: 1166441,
      total_submitted: 2553878,
      frontend_question_id: 16,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: '3Sum Closest',
    url: 'https://leetcode.com/problems/3sum-closest',
  },
  {
    stat: {
      question_id: 17,
      question__title: 'Letter Combinations of a Phone Number',
      question__title_slug: 'letter-combinations-of-a-phone-number',
      question__hide: false,
      total_acs: 1906801,
      total_submitted: 3189921,
      frontend_question_id: 17,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Letter Combinations of a Phone Number',
    url: 'https://leetcode.com/problems/letter-combinations-of-a-phone-number',
  },
  {
    stat: {
      question_id: 18,
      question__title: '4Sum',
      question__title_slug: '4sum',
      question__hide: false,
      total_acs: 894109,
      total_submitted: 2478848,
      frontend_question_id: 18,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: '4Sum',
    url: 'https://leetcode.com/problems/4sum',
  },
  {
    stat: {
      question_id: 19,
      question__title: 'Remove Nth Node From End of List',
      question__title_slug: 'remove-nth-node-from-end-of-list',
      question__hide: false,
      total_acs: 2442102,
      total_submitted: 5579369,
      frontend_question_id: 19,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Remove Nth Node From End of List',
    url: 'https://leetcode.com/problems/remove-nth-node-from-end-of-list',
  },
  {
    stat: {
      question_id: 20,
      question__title: 'Valid Parentheses',
      question__title_slug: 'valid-parentheses',
      question__hide: false,
      total_acs: 4251737,
      total_submitted: 10523588,
      frontend_question_id: 20,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Valid Parentheses',
    url: 'https://leetcode.com/problems/valid-parentheses',
  },
  {
    stat: {
      question_id: 21,
      question__title: 'Merge Two Sorted Lists',
      question__title_slug: 'merge-two-sorted-lists',
      question__hide: false,
      total_acs: 3901050,
      total_submitted: 6110252,
      frontend_question_id: 21,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Merge Two Sorted Lists',
    url: 'https://leetcode.com/problems/merge-two-sorted-lists',
  },
  {
    stat: {
      question_id: 22,
      question__title: 'Generate Parentheses',
      question__title_slug: 'generate-parentheses',
      question__hide: false,
      total_acs: 1698653,
      total_submitted: 2292461,
      frontend_question_id: 22,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Generate Parentheses',
    url: 'https://leetcode.com/problems/generate-parentheses',
  },
  {
    stat: {
      question_id: 23,
      question__title: 'Merge k Sorted Lists',
      question__title_slug: 'merge-k-sorted-lists',
      question__hide: false,
      total_acs: 1881708,
      total_submitted: 3617486,
      frontend_question_id: 23,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Merge k Sorted Lists',
    url: 'https://leetcode.com/problems/merge-k-sorted-lists',
  },
  {
    stat: {
      question_id: 24,
      question__title: 'Swap Nodes in Pairs',
      question__title_slug: 'swap-nodes-in-pairs',
      question__hide: false,
      total_acs: 1301198,
      total_submitted: 2037930,
      frontend_question_id: 24,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Swap Nodes in Pairs',
    url: 'https://leetcode.com/problems/swap-nodes-in-pairs',
  },
  {
    stat: {
      question_id: 25,
      question__title: 'Reverse Nodes in k-Group',
      question__title_slug: 'reverse-nodes-in-k-group',
      question__hide: false,
      total_acs: 859325,
      total_submitted: 1485764,
      frontend_question_id: 25,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Reverse Nodes in k-Group',
    url: 'https://leetcode.com/problems/reverse-nodes-in-k-group',
  },
  {
    stat: {
      question_id: 26,
      question__title: 'Remove Duplicates from Sorted Array',
      question__title_slug: 'remove-duplicates-from-sorted-array',
      question__hide: false,
      total_acs: 3928421,
      total_submitted: 7187531,
      frontend_question_id: 26,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Remove Duplicates from Sorted Array',
    url: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array',
  },
  {
    stat: {
      question_id: 27,
      question__title: 'Remove Element',
      question__title_slug: 'remove-element',
      question__hide: false,
      total_acs: 2576559,
      total_submitted: 4605528,
      frontend_question_id: 27,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Remove Element',
    url: 'https://leetcode.com/problems/remove-element',
  },
  {
    stat: {
      question_id: 28,
      question__title: 'Find the Index of the First Occurrence in a String',
      question__title_slug: 'find-the-index-of-the-first-occurrence-in-a-string',
      question__hide: false,
      total_acs: 2254027,
      total_submitted: 5411241,
      frontend_question_id: 28,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Find the Index of the First Occurrence in a String',
    url: 'https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string',
  },
  {
    stat: {
      question_id: 29,
      question__title: 'Divide Two Integers',
      question__title_slug: 'divide-two-integers',
      question__hide: false,
      total_acs: 696744,
      total_submitted: 4039630,
      frontend_question_id: 29,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Divide Two Integers',
    url: 'https://leetcode.com/problems/divide-two-integers',
  },
  {
    stat: {
      question_id: 30,
      question__title: 'Substring with Concatenation of All Words',
      question__title_slug: 'substring-with-concatenation-of-all-words',
      question__hide: false,
      total_acs: 414694,
      total_submitted: 1294129,
      frontend_question_id: 30,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Substring with Concatenation of All Words',
    url: 'https://leetcode.com/problems/substring-with-concatenation-of-all-words',
  },
  {
    stat: {
      question_id: 31,
      question__title: 'Next Permutation',
      question__title_slug: 'next-permutation',
      question__hide: false,
      total_acs: 1254587,
      total_submitted: 3189685,
      frontend_question_id: 31,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Next Permutation',
    url: 'https://leetcode.com/problems/next-permutation',
  },
  {
    stat: {
      question_id: 32,
      question__title: 'Longest Valid Parentheses',
      question__title_slug: 'longest-valid-parentheses',
      question__hide: false,
      total_acs: 699969,
      total_submitted: 2076976,
      frontend_question_id: 32,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Longest Valid Parentheses',
    url: 'https://leetcode.com/problems/longest-valid-parentheses',
  },
  {
    stat: {
      question_id: 33,
      question__title: 'Search in Rotated Sorted Array',
      question__title_slug: 'search-in-rotated-sorted-array',
      question__hide: false,
      total_acs: 2556343,
      total_submitted: 6327321,
      frontend_question_id: 33,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Search in Rotated Sorted Array',
    url: 'https://leetcode.com/problems/search-in-rotated-sorted-array',
  },
  {
    stat: {
      question_id: 34,
      question__title: 'Find First and Last Position of Element in Sorted Array',
      question__title_slug: 'find-first-and-last-position-of-element-in-sorted-array',
      question__hide: false,
      total_acs: 1911147,
      total_submitted: 4355956,
      frontend_question_id: 34,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Find First and Last Position of Element in Sorted Array',
    url: 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array',
  },
  {
    stat: {
      question_id: 35,
      question__title: 'Search Insert Position',
      question__title_slug: 'search-insert-position',
      question__hide: false,
      total_acs: 2671655,
      total_submitted: 5898306,
      frontend_question_id: 35,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Search Insert Position',
    url: 'https://leetcode.com/problems/search-insert-position',
  },
  {
    stat: {
      question_id: 36,
      question__title: 'Valid Sudoku',
      question__title_slug: 'valid-sudoku',
      question__hide: false,
      total_acs: 1397359,
      total_submitted: 2358884,
      frontend_question_id: 36,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Valid Sudoku',
    url: 'https://leetcode.com/problems/valid-sudoku',
  },
  {
    stat: {
      question_id: 37,
      question__title: 'Sudoku Solver',
      question__title_slug: 'sudoku-solver',
      question__hide: false,
      total_acs: 546636,
      total_submitted: 907203,
      frontend_question_id: 37,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Sudoku Solver',
    url: 'https://leetcode.com/problems/sudoku-solver',
  },
  {
    stat: {
      question_id: 38,
      question__title: 'Count and Say',
      question__title_slug: 'count-and-say',
      question__hide: false,
      total_acs: 880699,
      total_submitted: 1622501,
      frontend_question_id: 38,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Count and Say',
    url: 'https://leetcode.com/problems/count-and-say',
  },
  {
    stat: {
      question_id: 39,
      question__title: 'Combination Sum',
      question__title_slug: 'combination-sum',
      question__hide: false,
      total_acs: 1797074,
      total_submitted: 2536809,
      frontend_question_id: 39,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Combination Sum',
    url: 'https://leetcode.com/problems/combination-sum',
  },
  {
    stat: {
      question_id: 40,
      question__title: 'Combination Sum II',
      question__title_slug: 'combination-sum-ii',
      question__hide: false,
      total_acs: 905375,
      total_submitted: 1672522,
      frontend_question_id: 40,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Combination Sum II',
    url: 'https://leetcode.com/problems/combination-sum-ii',
  },
  {
    stat: {
      question_id: 41,
      question__title: 'First Missing Positive',
      question__title_slug: 'first-missing-positive',
      question__hide: false,
      total_acs: 1021499,
      total_submitted: 2710324,
      frontend_question_id: 41,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'First Missing Positive',
    url: 'https://leetcode.com/problems/first-missing-positive',
  },
  {
    stat: {
      question_id: 42,
      question__title: 'Trapping Rain Water',
      question__title_slug: 'trapping-rain-water',
      question__hide: false,
      total_acs: 1864358,
      total_submitted: 3075024,
      frontend_question_id: 42,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Trapping Rain Water',
    url: 'https://leetcode.com/problems/trapping-rain-water',
  },
  {
    stat: {
      question_id: 43,
      question__title: 'Multiply Strings',
      question__title_slug: 'multiply-strings',
      question__hide: false,
      total_acs: 752062,
      total_submitted: 1881658,
      frontend_question_id: 43,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Multiply Strings',
    url: 'https://leetcode.com/problems/multiply-strings',
  },
  {
    stat: {
      question_id: 44,
      question__title: 'Wildcard Matching',
      question__title_slug: 'wildcard-matching',
      question__hide: false,
      total_acs: 540623,
      total_submitted: 1959631,
      frontend_question_id: 44,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Wildcard Matching',
    url: 'https://leetcode.com/problems/wildcard-matching',
  },
  {
    stat: {
      question_id: 45,
      question__title: 'Jump Game II',
      question__title_slug: 'jump-game-ii',
      question__hide: false,
      total_acs: 1134581,
      total_submitted: 2813549,
      frontend_question_id: 45,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Jump Game II',
    url: 'https://leetcode.com/problems/jump-game-ii',
  },
  {
    stat: {
      question_id: 46,
      question__title: 'Permutations',
      question__title_slug: 'permutations',
      question__hide: false,
      total_acs: 1948715,
      total_submitted: 2501652,
      frontend_question_id: 46,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Permutations',
    url: 'https://leetcode.com/problems/permutations',
  },
  {
    stat: {
      question_id: 47,
      question__title: 'Permutations II',
      question__title_slug: 'permutations-ii',
      question__hide: false,
      total_acs: 883809,
      total_submitted: 1505568,
      frontend_question_id: 47,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Permutations II',
    url: 'https://leetcode.com/problems/permutations-ii',
  },
  {
    stat: {
      question_id: 48,
      question__title: 'Rotate Image',
      question__title_slug: 'rotate-image',
      question__hide: false,
      total_acs: 1582816,
      total_submitted: 2149388,
      frontend_question_id: 48,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Rotate Image',
    url: 'https://leetcode.com/problems/rotate-image',
  },
  {
    stat: {
      question_id: 49,
      question__title: 'Group Anagrams',
      question__title_slug: 'group-anagrams',
      question__hide: false,
      total_acs: 2643612,
      total_submitted: 3879612,
      frontend_question_id: 49,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Group Anagrams',
    url: 'https://leetcode.com/problems/group-anagrams',
  },
  {
    stat: {
      question_id: 50,
      question__title: 'Pow(x, n)',
      question__title_slug: 'powx-n',
      question__hide: false,
      total_acs: 1531315,
      total_submitted: 4452970,
      frontend_question_id: 50,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Pow(x, n)',
    url: 'https://leetcode.com/problems/powx-n',
  },
  {
    stat: {
      question_id: 51,
      question__title: 'N-Queens',
      question__title_slug: 'n-queens',
      question__hide: false,
      total_acs: 670381,
      total_submitted: 994117,
      frontend_question_id: 51,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'N-Queens',
    url: 'https://leetcode.com/problems/n-queens',
  },
  {
    stat: {
      question_id: 52,
      question__title: 'N-Queens II',
      question__title_slug: 'n-queens-ii',
      question__hide: false,
      total_acs: 360738,
      total_submitted: 491971,
      frontend_question_id: 52,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'N-Queens II',
    url: 'https://leetcode.com/problems/n-queens-ii',
  },
  {
    stat: {
      question_id: 53,
      question__title: 'Maximum Subarray',
      question__title_slug: 'maximum-subarray',
      question__hide: false,
      total_acs: 3668436,
      total_submitted: 7254158,
      frontend_question_id: 53,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Maximum Subarray',
    url: 'https://leetcode.com/problems/maximum-subarray',
  },
  {
    stat: {
      question_id: 54,
      question__title: 'Spiral Matrix',
      question__title_slug: 'spiral-matrix',
      question__hide: false,
      total_acs: 1319329,
      total_submitted: 2709270,
      frontend_question_id: 54,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Spiral Matrix',
    url: 'https://leetcode.com/problems/spiral-matrix',
  },
  {
    stat: {
      question_id: 55,
      question__title: 'Jump Game',
      question__title_slug: 'jump-game',
      question__hide: false,
      total_acs: 1743881,
      total_submitted: 4527626,
      frontend_question_id: 55,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Jump Game',
    url: 'https://leetcode.com/problems/jump-game',
  },
  {
    stat: {
      question_id: 56,
      question__title: 'Merge Intervals',
      question__title_slug: 'merge-intervals',
      question__hide: false,
      total_acs: 2229088,
      total_submitted: 4747064,
      frontend_question_id: 56,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Merge Intervals',
    url: 'https://leetcode.com/problems/merge-intervals',
  },
  {
    stat: {
      question_id: 57,
      question__title: 'Insert Interval',
      question__title_slug: 'insert-interval',
      question__hide: false,
      total_acs: 935930,
      total_submitted: 2348385,
      frontend_question_id: 57,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Insert Interval',
    url: 'https://leetcode.com/problems/insert-interval',
  },
  {
    stat: {
      question_id: 58,
      question__title: 'Length of Last Word',
      question__title_slug: 'length-of-last-word',
      question__hide: false,
      total_acs: 1611459,
      total_submitted: 3319735,
      frontend_question_id: 58,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Length of Last Word',
    url: 'https://leetcode.com/problems/length-of-last-word',
  },
  {
    stat: {
      question_id: 59,
      question__title: 'Spiral Matrix II',
      question__title_slug: 'spiral-matrix-ii',
      question__hide: false,
      total_acs: 549013,
      total_submitted: 776588,
      frontend_question_id: 59,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Spiral Matrix II',
    url: 'https://leetcode.com/problems/spiral-matrix-ii',
  },
  {
    stat: {
      question_id: 60,
      question__title: 'Permutation Sequence',
      question__title_slug: 'permutation-sequence',
      question__hide: false,
      total_acs: 374627,
      total_submitted: 809152,
      frontend_question_id: 60,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Permutation Sequence',
    url: 'https://leetcode.com/problems/permutation-sequence',
  },
  {
    stat: {
      question_id: 61,
      question__title: 'Rotate List',
      question__title_slug: 'rotate-list',
      question__hide: false,
      total_acs: 885713,
      total_submitted: 2373018,
      frontend_question_id: 61,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Rotate List',
    url: 'https://leetcode.com/problems/rotate-list',
  },
  {
    stat: {
      question_id: 62,
      question__title: 'Unique Paths',
      question__title_slug: 'unique-paths',
      question__hide: false,
      total_acs: 1717828,
      total_submitted: 2682939,
      frontend_question_id: 62,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Unique Paths',
    url: 'https://leetcode.com/problems/unique-paths',
  },
  {
    stat: {
      question_id: 63,
      question__title: 'Unique Paths II',
      question__title_slug: 'unique-paths-ii',
      question__hide: false,
      total_acs: 874432,
      total_submitted: 2118314,
      frontend_question_id: 63,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Unique Paths II',
    url: 'https://leetcode.com/problems/unique-paths-ii',
  },
  {
    stat: {
      question_id: 64,
      question__title: 'Minimum Path Sum',
      question__title_slug: 'minimum-path-sum',
      question__hide: false,
      total_acs: 1100539,
      total_submitted: 1734440,
      frontend_question_id: 64,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Minimum Path Sum',
    url: 'https://leetcode.com/problems/minimum-path-sum',
  },
  {
    stat: {
      question_id: 65,
      question__title: 'Valid Number',
      question__title_slug: 'valid-number',
      question__hide: false,
      total_acs: 342020,
      total_submitted: 1762600,
      frontend_question_id: 65,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Valid Number',
    url: 'https://leetcode.com/problems/valid-number',
  },
  {
    stat: {
      question_id: 66,
      question__title: 'Plus One',
      question__title_slug: 'plus-one',
      question__hide: false,
      total_acs: 2081341,
      total_submitted: 4643310,
      frontend_question_id: 66,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Plus One',
    url: 'https://leetcode.com/problems/plus-one',
  },
  {
    stat: {
      question_id: 67,
      question__title: 'Add Binary',
      question__title_slug: 'add-binary',
      question__hide: false,
      total_acs: 1369007,
      total_submitted: 2575260,
      frontend_question_id: 67,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Add Binary',
    url: 'https://leetcode.com/problems/add-binary',
  },
  {
    stat: {
      question_id: 68,
      question__title: 'Text Justification',
      question__title_slug: 'text-justification',
      question__hide: false,
      total_acs: 387682,
      total_submitted: 912634,
      frontend_question_id: 68,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Text Justification',
    url: 'https://leetcode.com/problems/text-justification',
  },
  {
    stat: {
      question_id: 69,
      question__title: 'Sqrt(x)',
      question__title_slug: 'sqrtx',
      question__hide: false,
      total_acs: 1816145,
      total_submitted: 4727655,
      frontend_question_id: 69,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Sqrt(x)',
    url: 'https://leetcode.com/problems/sqrtx',
  },
  {
    stat: {
      question_id: 70,
      question__title: 'Climbing Stairs',
      question__title_slug: 'climbing-stairs',
      question__hide: false,
      total_acs: 3031347,
      total_submitted: 5740085,
      frontend_question_id: 70,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Climbing Stairs',
    url: 'https://leetcode.com/problems/climbing-stairs',
  },
  {
    stat: {
      question_id: 71,
      question__title: 'Simplify Path',
      question__title_slug: 'simplify-path',
      question__hide: false,
      total_acs: 690481,
      total_submitted: 1653639,
      frontend_question_id: 71,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Simplify Path',
    url: 'https://leetcode.com/problems/simplify-path',
  },
  {
    stat: {
      question_id: 72,
      question__title: 'Edit Distance',
      question__title_slug: 'edit-distance',
      question__hide: false,
      total_acs: 797613,
      total_submitted: 1424664,
      frontend_question_id: 72,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Edit Distance',
    url: 'https://leetcode.com/problems/edit-distance',
  },
  {
    stat: {
      question_id: 73,
      question__title: 'Set Matrix Zeroes',
      question__title_slug: 'set-matrix-zeroes',
      question__hide: false,
      total_acs: 1287360,
      total_submitted: 2350404,
      frontend_question_id: 73,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Set Matrix Zeroes',
    url: 'https://leetcode.com/problems/set-matrix-zeroes',
  },
  {
    stat: {
      question_id: 74,
      question__title: 'Search a 2D Matrix',
      question__title_slug: 'search-a-2d-matrix',
      question__hide: false,
      total_acs: 1642908,
      total_submitted: 3305443,
      frontend_question_id: 74,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Search a 2D Matrix',
    url: 'https://leetcode.com/problems/search-a-2d-matrix',
  },
  {
    stat: {
      question_id: 75,
      question__title: 'Sort Colors',
      question__title_slug: 'sort-colors',
      question__hide: false,
      total_acs: 1784122,
      total_submitted: 2901090,
      frontend_question_id: 75,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Sort Colors',
    url: 'https://leetcode.com/problems/sort-colors',
  },
  {
    stat: {
      question_id: 76,
      question__title: 'Minimum Window Substring',
      question__title_slug: 'minimum-window-substring',
      question__hide: false,
      total_acs: 1270722,
      total_submitted: 2978194,
      frontend_question_id: 76,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Minimum Window Substring',
    url: 'https://leetcode.com/problems/minimum-window-substring',
  },
  {
    stat: {
      question_id: 77,
      question__title: 'Combinations',
      question__title_slug: 'combinations',
      question__hide: false,
      total_acs: 852617,
      total_submitted: 1219172,
      frontend_question_id: 77,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Combinations',
    url: 'https://leetcode.com/problems/combinations',
  },
  {
    stat: {
      question_id: 78,
      question__title: 'Subsets',
      question__title_slug: 'subsets',
      question__hide: false,
      total_acs: 1727617,
      total_submitted: 2245255,
      frontend_question_id: 78,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Subsets',
    url: 'https://leetcode.com/problems/subsets',
  },
  {
    stat: {
      question_id: 79,
      question__title: 'Word Search',
      question__title_slug: 'word-search',
      question__hide: false,
      total_acs: 1474050,
      total_submitted: 3571747,
      frontend_question_id: 79,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Word Search',
    url: 'https://leetcode.com/problems/word-search',
  },
  {
    stat: {
      question_id: 80,
      question__title: 'Remove Duplicates from Sorted Array II',
      question__title_slug: 'remove-duplicates-from-sorted-array-ii',
      question__hide: false,
      total_acs: 821169,
      total_submitted: 1438493,
      frontend_question_id: 80,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Remove Duplicates from Sorted Array II',
    url: 'https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii',
  },
  {
    stat: {
      question_id: 81,
      question__title: 'Search in Rotated Sorted Array II',
      question__title_slug: 'search-in-rotated-sorted-array-ii',
      question__hide: false,
      total_acs: 678523,
      total_submitted: 1812208,
      frontend_question_id: 81,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Search in Rotated Sorted Array II',
    url: 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii',
  },
  {
    stat: {
      question_id: 82,
      question__title: 'Remove Duplicates from Sorted List II',
      question__title_slug: 'remove-duplicates-from-sorted-list-ii',
      question__hide: false,
      total_acs: 693771,
      total_submitted: 1474951,
      frontend_question_id: 82,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Remove Duplicates from Sorted List II',
    url: 'https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii',
  },
  {
    stat: {
      question_id: 83,
      question__title: 'Remove Duplicates from Sorted List',
      question__title_slug: 'remove-duplicates-from-sorted-list',
      question__hide: false,
      total_acs: 1422314,
      total_submitted: 2731371,
      frontend_question_id: 83,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Remove Duplicates from Sorted List',
    url: 'https://leetcode.com/problems/remove-duplicates-from-sorted-list',
  },
  {
    stat: {
      question_id: 84,
      question__title: 'Largest Rectangle in Histogram',
      question__title_slug: 'largest-rectangle-in-histogram',
      question__hide: false,
      total_acs: 821575,
      total_submitted: 1869995,
      frontend_question_id: 84,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Largest Rectangle in Histogram',
    url: 'https://leetcode.com/problems/largest-rectangle-in-histogram',
  },
  {
    stat: {
      question_id: 85,
      question__title: 'Maximal Rectangle',
      question__title_slug: 'maximal-rectangle',
      question__hide: false,
      total_acs: 386617,
      total_submitted: 830163,
      frontend_question_id: 85,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Maximal Rectangle',
    url: 'https://leetcode.com/problems/maximal-rectangle',
  },
  {
    stat: {
      question_id: 86,
      question__title: 'Partition List',
      question__title_slug: 'partition-list',
      question__hide: false,
      total_acs: 589695,
      total_submitted: 1057369,
      frontend_question_id: 86,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Partition List',
    url: 'https://leetcode.com/problems/partition-list',
  },
  {
    stat: {
      question_id: 87,
      question__title: 'Scramble String',
      question__title_slug: 'scramble-string',
      question__hide: false,
      total_acs: 221087,
      total_submitted: 556247,
      frontend_question_id: 87,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 3,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Scramble String',
    url: 'https://leetcode.com/problems/scramble-string',
  },
  {
    stat: {
      question_id: 88,
      question__title: 'Merge Sorted Array',
      question__title_slug: 'merge-sorted-array',
      question__hide: false,
      total_acs: 2813775,
      total_submitted: 5747704,
      frontend_question_id: 88,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Merge Sorted Array',
    url: 'https://leetcode.com/problems/merge-sorted-array',
  },
  {
    stat: {
      question_id: 89,
      question__title: 'Gray Code',
      question__title_slug: 'gray-code',
      question__hide: false,
      total_acs: 285238,
      total_submitted: 486888,
      frontend_question_id: 89,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Gray Code',
    url: 'https://leetcode.com/problems/gray-code',
  },
  {
    stat: {
      question_id: 90,
      question__title: 'Subsets II',
      question__title_slug: 'subsets-ii',
      question__hide: false,
      total_acs: 856760,
      total_submitted: 1504713,
      frontend_question_id: 90,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Subsets II',
    url: 'https://leetcode.com/problems/subsets-ii',
  },
  {
    stat: {
      question_id: 91,
      question__title: 'Decode Ways',
      question__title_slug: 'decode-ways',
      question__hide: false,
      total_acs: 1205643,
      total_submitted: 3484752,
      frontend_question_id: 91,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Decode Ways',
    url: 'https://leetcode.com/problems/decode-ways',
  },
  {
    stat: {
      question_id: 92,
      question__title: 'Reverse Linked List II',
      question__title_slug: 'reverse-linked-list-ii',
      question__hide: false,
      total_acs: 813622,
      total_submitted: 1715243,
      frontend_question_id: 92,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Reverse Linked List II',
    url: 'https://leetcode.com/problems/reverse-linked-list-ii',
  },
  {
    stat: {
      question_id: 93,
      question__title: 'Restore IP Addresses',
      question__title_slug: 'restore-ip-addresses',
      question__hide: false,
      total_acs: 440378,
      total_submitted: 893527,
      frontend_question_id: 93,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Restore IP Addresses',
    url: 'https://leetcode.com/problems/restore-ip-addresses',
  },
  {
    stat: {
      question_id: 94,
      question__title: 'Binary Tree Inorder Traversal',
      question__title_slug: 'binary-tree-inorder-traversal',
      question__hide: false,
      total_acs: 2397020,
      total_submitted: 3164685,
      frontend_question_id: 94,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Binary Tree Inorder Traversal',
    url: 'https://leetcode.com/problems/binary-tree-inorder-traversal',
  },
  {
    stat: {
      question_id: 95,
      question__title: 'Unique Binary Search Trees II',
      question__title_slug: 'unique-binary-search-trees-ii',
      question__hide: false,
      total_acs: 438045,
      total_submitted: 765395,
      frontend_question_id: 95,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Unique Binary Search Trees II',
    url: 'https://leetcode.com/problems/unique-binary-search-trees-ii',
  },
  {
    stat: {
      question_id: 96,
      question__title: 'Unique Binary Search Trees',
      question__title_slug: 'unique-binary-search-trees',
      question__hide: false,
      total_acs: 637630,
      total_submitted: 1049298,
      frontend_question_id: 96,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Unique Binary Search Trees',
    url: 'https://leetcode.com/problems/unique-binary-search-trees',
  },
  {
    stat: {
      question_id: 97,
      question__title: 'Interleaving String',
      question__title_slug: 'interleaving-string',
      question__hide: false,
      total_acs: 494938,
      total_submitted: 1247968,
      frontend_question_id: 97,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Interleaving String',
    url: 'https://leetcode.com/problems/interleaving-string',
  },
  {
    stat: {
      question_id: 98,
      question__title: 'Validate Binary Search Tree',
      question__title_slug: 'validate-binary-search-tree',
      question__hide: false,
      total_acs: 2218397,
      total_submitted: 6788111,
      frontend_question_id: 98,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Validate Binary Search Tree',
    url: 'https://leetcode.com/problems/validate-binary-search-tree',
  },
  {
    stat: {
      question_id: 99,
      question__title: 'Recover Binary Search Tree',
      question__title_slug: 'recover-binary-search-tree',
      question__hide: false,
      total_acs: 435842,
      total_submitted: 828058,
      frontend_question_id: 99,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 2,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Recover Binary Search Tree',
    url: 'https://leetcode.com/problems/recover-binary-search-tree',
  },
  {
    stat: {
      question_id: 100,
      question__title: 'Same Tree',
      question__title_slug: 'same-tree',
      question__hide: false,
      total_acs: 1903884,
      total_submitted: 3139047,
      frontend_question_id: 100,
      is_new_question: false,
    },
    status: null,
    difficulty: {
      level: 1,
    },
    paid_only: false,
    frequency: 0,
    progress: 0,
    title: 'Same Tree',
    url: 'https://leetcode.com/problems/same-tree',
  },
] as const
